# Generated by Django 4.0 on 2021-12-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Country Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Recipe Name')),
                ('image', models.ImageField(default='static/images/default_dish.jpg', upload_to='static/images/', verbose_name='Picture of the Dish')),
                ('recipe', models.TextField(verbose_name='Recipe of the Dish')),
                ('servings', models.PositiveSmallIntegerField(default=1, verbose_name='Number of Servings')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World_Cooking_App.category', verbose_name='Category of the Dish')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Ingredient Name')),
                ('quantity', models.CharField(max_length=50, verbose_name='Ingredient Quantity')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World_Cooking_App.dish', verbose_name='Dish of the Ingredient')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
