# Generated by Django 4.0 on 2022-01-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cooking_App', '0005_category_img_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_url',
            field=models.URLField(default='img_url', max_length=500),
        ),
        migrations.AddField(
            model_name='dish',
            name='img_url',
            field=models.URLField(default='img_url', max_length=500),
        ),
    ]
