# Generated by Django 4.0 on 2022-01-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cooking_App', '0006_category_img_url_dish_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.URLField(default='img_url', max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='img_url',
            field=models.URLField(default='img_url', max_length=500, verbose_name='Image URL'),
        ),
    ]
