# Generated by Django 4.0 on 2022-01-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cooking_App', '0007_alter_category_img_url_alter_dish_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
