# Generated by Django 4.0 on 2022-01-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Cooking_App', '0008_remove_category_img_remove_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ingredient Name'),
        ),
    ]
